services:
  playlistdl:
    image: tanner23456/playlistdl:v2
    container_name: playlistdl
    ports:
      - "8800:5000"
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

      - AUDIO_DOWNLOAD_PATH=/music
      - CLEANUP_INTERVAL=300
    volumes:
      - M:/playlist_music:/music