services:
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - "5454:5454"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - F:/docker_configs/notifiarr/config:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    annotations:
    - "com.centurylinklabs.watchtower.enable=true"
  dockwatch:
    container_name: dockwatch
    image: ghcr.io/notifiarr/dockwatch:latest
    ports:
      - "3006:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - F:/docker_configs/dockwatch/config:/config
    restart: unless-stopped
    annotations:
    - "com.centurylinklabs.watchtower.enable=true"