version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - TZ=Europe/Zurich
    volumes:
      - F:/docker_configs/slskd/config:/app
      - M:/downloads:/downloads
    restart: always
    labels:
     - "com.centurylinklabs.watchtower.enable=true"